"""Add template_link column to contests table

Revision ID: 537a7ac92f55
Revises: 1fa03cdd51b
Create Date: 2025-12-30 12:27:03.870577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537a7ac92f55'
down_revision = '1fa03cdd51b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contests', sa.Column('template_link', sa.Text(), nullable=True))
    op.drop_index(op.f('idx_user_contest_submission'), table_name='submissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_user_contest_submission'), 'submissions', ['user_id', 'contest_id'], unique=False)
    op.drop_column('contests', 'template_link')
    # ### end Alembic commands ###

