"""Add template_link column to contests table and Add OAuth token columns to users table and Add template_added column to submissions table

Revision ID: 5390fc3ff139
Revises: 30c4f4dbcb85
Create Date: 2026-01-14 00:10:27.930480

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5390fc3ff139'
down_revision = '30c4f4dbcb85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contests', sa.Column('template_link', sa.Text(), nullable=True))
    op.alter_column('contests', 'scoring_parameters',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               comment=None,
               existing_comment='Weights for scoring parameters',
               existing_nullable=True)
    op.alter_column('contests', 'min_reference_count',
               existing_type=mysql.INTEGER(),
               server_default=None,
               comment=None,
               existing_comment='Minimum number of references required for article submissions',
               existing_nullable=False)
    op.alter_column('contests', 'organizers',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='Comma-separated list of organizer usernames',
               existing_nullable=True)
    op.add_column('submissions', sa.Column('template_added', sa.Boolean(), nullable=True))
    op.alter_column('submissions', 'parameter_scores',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               comment=None,
               existing_comment='Per-parameter jury scores and comments',
               existing_nullable=True)
    op.drop_index(op.f('idx_user_contest_submission'), table_name='submissions')
    op.add_column('users', sa.Column('oauth_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('oauth_token_secret', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'oauth_token_secret')
    op.drop_column('users', 'oauth_token')
    op.create_index(op.f('idx_user_contest_submission'), 'submissions', ['user_id', 'contest_id'], unique=False)
    op.alter_column('submissions', 'parameter_scores',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               comment='Per-parameter jury scores and comments',
               existing_nullable=True)
    op.drop_column('submissions', 'template_added')
    op.alter_column('contests', 'organizers',
               existing_type=mysql.TEXT(),
               comment='Comma-separated list of organizer usernames',
               existing_nullable=True)
    op.alter_column('contests', 'min_reference_count',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               comment='Minimum number of references required for article submissions',
               existing_nullable=False)
    op.alter_column('contests', 'scoring_parameters',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               comment='Weights for scoring parameters',
               existing_nullable=True)
    op.drop_column('contests', 'template_link')
    # ### end Alembic commands ###

