"""Add template_added column to submissions table

Revision ID: 79fec21a9349
Revises: a4501b0bf048
Create Date: 2025-12-30 12:39:16.388276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79fec21a9349'
down_revision = 'a4501b0bf048'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('template_added', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'template_added')
    # ### end Alembic commands ###

