"""remove extra line

Revision ID: 7fc823789534
Revises: ea8b4c071516
Create Date: 2026-01-14 20:41:56.695468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc823789534'
down_revision = 'ea8b4c071516'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

