"""Add categories_added and category_error columns to submissions table

Revision ID: ed3dabd7833f
Revises: c4d1d7879989
Create Date: 2026-01-14 16:17:46.783789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed3dabd7833f'
down_revision = 'c4d1d7879989'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contests', sa.Column('template_link', sa.Text(), nullable=True))
    op.alter_column('contests', 'scoring_parameters',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='Weights for scoring parameters',
               existing_nullable=True)
    op.alter_column('contests', 'min_reference_count',
               existing_type=mysql.INTEGER(),
               server_default=None,
               comment=None,
               existing_comment='Minimum number of references required for article submissions',
               existing_nullable=False)
    op.alter_column('contests', 'organizers',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='Comma-separated list of organizer usernames',
               existing_nullable=True)
    op.add_column('submissions', sa.Column('template_added', sa.Boolean(), nullable=True))
    op.add_column('submissions', sa.Column('categories_added', sa.Text(), nullable=True))
    op.add_column('submissions', sa.Column('category_error', sa.Text(), nullable=True))
    op.alter_column('submissions', 'parameter_scores',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='Per-parameter jury scores and comments',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'parameter_scores',
               existing_type=mysql.TEXT(),
               comment='Per-parameter jury scores and comments',
               existing_nullable=True)
    op.drop_column('submissions', 'category_error')
    op.drop_column('submissions', 'categories_added')
    op.drop_column('submissions', 'template_added')
    op.alter_column('contests', 'organizers',
               existing_type=mysql.TEXT(),
               comment='Comma-separated list of organizer usernames',
               existing_nullable=True)
    op.alter_column('contests', 'min_reference_count',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               comment='Minimum number of references required for article submissions',
               existing_nullable=False)
    op.alter_column('contests', 'scoring_parameters',
               existing_type=mysql.TEXT(),
               comment='Weights for scoring parameters',
               existing_nullable=True)
    op.drop_column('contests', 'template_link')
    # ### end Alembic commands ###

